### ISSUE TITLE
PERIODIC ATTESTATION FAILED

### ISSUE THREAD

**Issue by abusm4n** [Fraunhofer-SIT/charra#70]
Hello Charra team,

I have enabled periodic attestation in the verifier.c file, (by uncommenting the necessary lines) however the **ATTESTATION IS FAILED** with the following error:

**ERROR src/verifier.c:678: [verifier]     => Nonce in TPM Quote is NOT valid! (does not match the one sent)**

Thanks in advance.

**Comment by abahmadb** [comment]
tbd

**Comment by eckelmeckel** [comment]
Hi @abahmadb,

thanks for pointing that out. We will look into this soon and come back to you.

Thanks,
@eckelmeckel

**Comment by eckelmeckel** [comment]
In my setup (using the CHARRA Docker container), uncommenting the periodic attestation leads to the expected result: periodic attestation. This feature is planned to be added in future versions and can then be configured via the command line interface.
